Informações Bruna Jesus
marcosalles/arbyte-alunos-e-contatos pull request #20
Opened 2020-07-01 23:27 UTC by bgdj17

2020-07-01 23:58 UTC, marcosalles requested changes

2020-07-01 23:58 UTC, marcosalles commented on index.html
> +							<img src="img/bruna.jpg" alt="fotoPerfil" class="profile-picture">
Você subiu uma imagem chamada `brunaJesus.jpg` mas aqui colocou só `bruna.jpg`. Não vai aparecer! Muda aqui  e sucesso!

2020-07-02 01:07 UTC, bgdj17 commented on index.html
> +							<img src="img/bruna.jpg" alt="fotoPerfil" class="profile-picture">
Eu tinha realizado a alteração do nome da imagem e esqueci de alterar no index.

2020-07-06 16:46 UTC, marcosalles approved these changes
Aeee =D

2020-07-06 16:46 UTC, merged