Felipe.teodoro
marcosalles/arbyte-alunos-e-contatos pull request #21
Opened 2020-07-01 23:28 UTC by FelipeTeodoro1991

Adicionando informações do aluno Felipe Teodoro

2020-07-02 00:04 UTC, marcosalles requested changes

2020-07-02 00:04 UTC, marcosalles commented on index.html
> +							<img src="img\felipeteodoro.png" alt="" class="profile-picture">
A barra aqui está invertida! Na web isso não vai funcionar direito, troca pra `/`

2020-07-02 23:49 UTC, FelipeTeodoro1991 commented on index.html
> +							<img src="img\felipeteodoro.png" alt="" class="profile-picture">
Problema resolvido

2020-07-02 23:50 UTC, FelipeTeodoro1991 commented
barra ja atualizada

2020-07-06 16:50 UTC, marcosalles approved these changes
Alterei no título do pull request pois ele vira a mensagem de commit. É muito importante títulos de pull request *descritivos*, pois quem vai ler nem sempre saberá o que você precisava fazer no código.

2020-07-06 16:50 UTC, merged